name: Core Gitflow CI Action workflow

on:
  push:
    # For GitFlow the following patterns are suggested:
    # - master
    # - develop
    # - feature/*
    # - release/*
    # - hotfix/*
    #
    # For an action with build_push_image=false the following patterns are suggested:
    # - master
    branches:
      - master

env:
  # AWS region of the AWS account storing images in AWS ECR.
  CORE_AWS_REGION: eu-north-1

jobs:
  gitflow-ci:
    name: Checkout main repository, run Gitflow CI action
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Checkout Gitflow CI action repository
        uses: actions/checkout@v4
        with:
          repository: edenlabllc/gitflow.ci.action
          ref: v1
          token: ${{ secrets.GH_TOKEN_REPO_FULL_ACCESS }}
          path: .github/actions/gitflow.ci.action

      - name: Run Gitflow CI action
        uses: ./.github/actions/gitflow.ci.action
        with:
          github_token_repo_full_access: ${{ secrets.GH_TOKEN_REPO_FULL_ACCESS }}
          build_push_image: false
